feat: replace x_gladia_key to x-gladia-key
gladiaio/gladia-samples pull request #12
Opened 2023-10-04 10:30 UTC by amorin-gladia

Pour le coup ça fait bizarre ...

Vous en pensez quoi ?

2023-10-04 12:04 UTC, nmorel commented
> Pour le coup ça fait bizarre ...
> 
> Vous en pensez quoi ?

Je suis d'accord, ça fait bizarre. On se retrouve avec un mélange de snake_case et kebab-case au sein du même objet JSON.  
Pour moi, le `x-gladia-key` est adapté pour l'api car c'est un header HTTP mais moins dans le cas d'une clé d'objet JSON.  
Surtout le préfixe `x-` qui est très spécifique header http.  

Pourquoi pas `gladia_key` ou `api_key` ?  
Après, pour info, on ne devrait plus avoir ce débat avec la v2 car on passera par un call api rest classique pour s'authentifier (plus de key ou de config à passer à la connexion WS).

2023-10-05 06:00 UTC, jsoto-gladia requested changes
possible to add a test please?

2023-10-05 14:02 UTC, amorin-gladia commented
Je suis d'accords avec toi Nicolas.
@jsoto-gladia Je close ?

2023-10-10 09:02 UTC, closed without merging

2023-10-10 09:02 UTC, amorin-gladia commented
not relevant anymore